### ISSUE TITLE
1. 데이터베이스 포르폴리오 테이블 이슈

### ISSUE THREAD

**Issue by dori-wooni** [kyj980303/project#1]
1. 저희 포트폴리오 등록시에 카테고리 설정하는 부분이 있는데, DB 상에는 포트폴리오 저장 시 해당 포트폴리오의 카테고리 정보를 저장할 칼럼이 지금 없다.

2. 포트폴리오 임시저장 화면도 있는데, 임시저장을 해놓으면 본인 말고 다른 사용자가 열람할 때 보이면 안되는데 그런 기능을 할 장치가 없다.

**Comment by PSyndiKate420** [comment]
1. 카테고리를 하나 더 만들면 해결할 수 있지만, 이렇게 해결할 시 자료가 지나치게 산발적일 수도 있어
    job(직업) table을 카테고리 table로 수정한 뒤 해당 table의 PK를 포트폴리오 table의 fk로 가져와 정보를 저장하고 싶습니다
3. 회원 번호를 fk로 가져와 해당 회원 번호가 아닐 시 열람하지 못하도록 하는 것이 어떨까요?

**Comment by dori-wooni** [comment]
1. 저희 포트폴리오 등록시에 카테고리 설정하는 부분이 있는데, DB 상에는 포트폴리오 저장 시 해당 포트폴리오의 카테고리 정보를 저장할 칼럼이 지금 없다.
: 재능판매카테고리 끌어오는 방안
: 카테고리 테이블 새로 만드는 방안

2. 포트폴리오 임시저장 화면도 있는데, 임시저장을 해놓으면 본인 말고 다른 사용자가 열람할 때 보이면 안되는데 그런 기능을 할 장치가 없다.
:  임시저장... 상부3조가 강사님한테 물어봤는데 테이블 따로 안넣어도되고 다른 기능으로 임시저장 만들수있다라고 설명해주심

		** 로컬스토리지 (LocalStorage)**
		로컬스토리지는 쿠키의 기능을 확장한 기능으로써
		데이터를 Key-Value 형태로 저장할 수도 있고, CRUD 자체가 쉽고 간편해서 좋은 것 같다.
		테스트해보니 브라우저를 껐다켜도, 세션을 지웠다해도 유지돼서 DB에 저장하긴 애매하고 또 데이터 유지는 해야겠고 싶을 때 활용하면 좋을듯!
:  디비에 게시물의 상태값 플래그로 처리하는 방법도있습니다
   : status : boolean True/False

**Comment by dori-wooni** [comment]
close
